<a href="https://colab.research.google.com/github/shivanshu5/python-practice/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# **PANDAS SERIES**
A Series is a one dimentional labeled array capable of holding any data type. the Axis labels are collectively called the index

# #Creating Series

there are multiple ways to create pasndas series:

```

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
labels = ["a","b","c"]
my_list = [12,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [ ]:
pd.Series(my_list)

0    12
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list,index=labels)

a    12
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# DataFrame
it combine multiple series

In [ ]:

data = {
      'Name': ['John', 'Anna', 'Peter', 'Linda'],
      'Age': [28, 34, 29, 42],
      'City': ['New York', 'Paris', 'Berlin', 'London'],
      'Salary': [65000, 70000, 62000, 85000]
                  }
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
['John', 28, 'New York', 65000],
['Anna', 34, 'Paris', 70000],
['Peter', 29, 'Berlin', 62000],
['Linda', 42, 'London', 85000]
 ]
df2 = pd.DataFrame(data_list)
df2
columns = ['Name', 'Age', 'City', 'Salary']
df2.columns = columns
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selection and indexing of a column

In [ ]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

# Create a column

In [ ]:
df2["Designation"] = ["doctor","engineer","teacher","doctor"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000     teacher
3  Linda   42    London   85000      doctor

# Remove a column

In [ ]:
#it only hide that column
df2.drop("Designation",axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#it  removes permanntly
df2.drop("Designation",axis=1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Remove a row

In [ ]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

# Selecting a row

In [ ]:
#for single row
df2.loc[0]

# for mutiple row
df2.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

# Selecting subset rows and columns

In [ ]:
#select a section
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

# Conditional

In [ ]:
#i wanted to see people whose age above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
#i wanted to see people whose age above 30 & place paris
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing data

In [ ]:
#Finding Missing data
data = {
'A': [1, 2, np.nan, 4, 5],
'B': [1, 2, 3, 4, 5],
'C': [1, 2, 3, np.nan, np.nan],
'D': [1, np.nan, np.nan, np.nan, 5]
 }
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# Removing Missing Data
it will drop row wise

In [ ]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
#Threshhold
#there sould be three non null values
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

# Filling Missing data
it will fill columnwise

In [ ]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
#filling different vlues for each columns
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [ ]:
#filling value with mean
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# Merging, Joining & Concatination

Merging :

In [ ]:
#merging two data frames
employees = pd.DataFrame({
'employee_id': [1, 2, 3, 4, 5],
'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
 })

 # DataFrame 2: Salary information
salaries = pd.DataFrame({
'employee_id': [1, 2, 3, 6, 7],
'salary': [60000, 80000, 65000, 70000, 90000],
                          'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

# concatination

In [ ]:
df1 = pd.DataFrame({
'A': ['A0', 'A1', 'A2'],
'B': ['B0', 'B1', 'B2'],
'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
'A': ['A3', 'A4', 'A5'],
 'B': ['B3', 'B4', 'B5'],
'C': ['C3', 'C4', 'C5']
}
)

In [ ]:
#on column basis
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
#on row basis
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# joining

In [ ]:
df1 = pd.DataFrame({
      'name': ['Alice', 'Bob', 'Charlie']
      }, index=[1, 2, 3])

      # Second DataFrame
df2 = pd.DataFrame({
          'score': [85, 90, 75]
          }, index=[2, 3, 4])

   score
2     85
3     90
4     75

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
#joining two dataframes
#inner join
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [ ]:
#joining two dataframes
#inner join
df2.join(df1,how ="outer")

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN

# Group BY Aggregation

In [ ]:
data = {
      'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
          'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
              'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
                  'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
                      'Date': pd.date_range('2023-01-01', periods=8)
                      }

In [ ]:
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
#Group bu category and calculate sum of sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
#Group By Store and calculate the sum of sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# Aggregation

In [ ]:
df['Sales'].mean()
'''mean, median, min, max, count, std '''

In [ ]:
df['Sales'].agg(['mean','min','max', 'count', 'sum', 'std'])

mean      187.500000
min       100.000000
max       300.000000
count       8.000000
sum      1500.000000
std        66.062741
Name: Sales, dtype: float64

# Pivot Table

In [ ]:
data = {
      'Date': pd.date_range('2023-01-01', periods=20),
          'Product': ['A', 'B', 'C', 'D'] * 5,
              'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
                             'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
                                 'Sales': np.random.randint(100, 1000, 20),
                                     'Units': np.random.randint(10, 100, 20),
                                         'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
                                                     'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
                                                     }

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    455     78   John  January      Q1
1  2023-01-02       B   West    335     44   Mary  January      Q1
2  2023-01-03       C  North    388     72    Bob  January      Q1
3  2023-01-04       D  South    295     21  Alice  January      Q1
4  2023-01-05       A   East    562     34   John  January      Q1
5  2023-01-06       B   West    481     29   Mary  January      Q1
6  2023-01-07       C  North    181     15    Bob  January      Q1
7  2023-01-08       D  South    512     29  Alice  January      Q1
8  2023-01-09       A   East    660     26   John  January      Q1
9  2023-01-10       B   West    401     44   Mary  January      Q1
10 2023-01-11       C  North    641     19    Bob  January      Q1
11 2023-01-12       D  South    733     39  Alice  January      Q1
12 2023-01-13       A   East    380     32   John  January      Q1
13 2023-01-14       B   West    172     34   Mary  January      Q1
14 2023-01-15       C  North    449     11    Bob  January      Q1
15 2023-01-16       D  South    259     57  Alice  January      Q1
16 2023-01-17       A   East    667     27   John  January      Q1
17 2023-01-18       B   West    676     10   Mary  January      Q1
18 2023-01-19       C  North    674     73    Bob  January      Q1
19 2023-01-20       D  South    629     91  Alice  January      Q1

In [64]:
pd.pivot_table(df,values="Sales", index = 'Region',columns="Product",aggfunc = "mean")

Product      A      B      C      D
Region
East     544.8    NaN    NaN    NaN
North      NaN    NaN  466.6    NaN
South      NaN    NaN    NaN  485.6
West       NaN  413.0    NaN    NaN

In [65]:
pd.pivot_table(df,values=["Sales","Units"], index = 'Region',columns="Product")

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     544.8    NaN    NaN    NaN  39.4   NaN   NaN   NaN
North      NaN    NaN  466.6    NaN   NaN   NaN  38.0   NaN
South      NaN    NaN    NaN  485.6   NaN   NaN   NaN  47.4
West       NaN  413.0    NaN    NaN   NaN  32.2   NaN   NaN

# CROSS TABS

In [67]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [69]:
#DataFrame Basic Operations
df1 = pd.DataFrame({
      'A': [1, 2, 3, 4, 5],
          'B': [10, 20, 30, 40, 50],
              'C': [100, 200, 300, 400, 500]
              })
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [70]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

#DataFrame APplying Functions

In [72]:
def square(x):
  return x**2

In [73]:
df1['D'] = df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500